### ISSUE TITLE
jquery support

### ISSUE THREAD

**Issue by robgalvinco** [sneas/img-comparison-slider#106]
Is there anyway to get this to work on an HTML page that uses jQuery?

**Comment by sneas** [comment]
This library should not conflict with jQuery. Here are installation steps: https://github.com/sneas/img-comparison-slider#html

**Comment by robgalvinco** [comment]
Thanks for quick reply - is there some method to initialize it? I placed code on a page and nothing happened

**Comment by sneas** [comment]
No, this library implements Web Components standarts, thus there is no need in a special initialization function to be called (in fact, there is no such a function).

Perhaps, I can help you to resolve the problem if you show me the non-working example.

**Comment by sneas** [comment]
Here is the the CodePen with a working example https://codepen.io/sneas/pen/JjBoPEO
