### ISSUE TITLE
drag not possible on mobile

### ISSUE THREAD

**Issue by FlorianLudwig** [sneas/img-comparison-slider#11]
On desktop I can either drag the middle or can click on any part to move it. On mobile only touch but no drag works.

**Comment by sneas** [comment]
Hi Florian, I have also recently discovered that issue. And it turned out the issue happens when an app's width is larger than 100%. It creates a horizontal scrollbar which affects the component work. I'm going to address this issue at some point, but I can't promise to fix this problem quickly. For now, as a workaround, I can recommend fixing the app's width so it is less or equal user screen's width. This will not only fix the existing problem with the component but will also positively affect user experience.

**Comment by FlorianLudwig** [comment]
Hey @sneas.

thank you for your quick answer! The app in question is your demo :) https://sneas.github.io/img-comparison-slider/

**Comment by sneas** [comment]
Haha, that's weird. May I ask what browser(s) are you using? I've just checked the demo with Chrome, FF, and Safari and it works fine for me.

"Works on my machine" syndrome™️

**Comment by FlorianLudwig** [comment]
@sneas I tried chrome and firefox on android.

**Comment by sneas** [comment]
Alright, thank you for reporting the issue, @FlorianLudwig ! I'll check this out as soon as I figure out how to run Android simulator from Android Studio 🤦‍♂️ That's a nasty bug! I've just tried the demo with Chrome on iOS and it works fine for me.

**Comment by FlorianLudwig** [comment]
AFAIK Chrome on iOS does uses safari for rendering.

Actually, I can reproduce this with chrome desktop, using the mobile emulation.

**Comment by sneas** [comment]
> AFAIK Chrome on iOS does uses safari for rendering.

You're right.

Let me check it on the emulator (hopefully this week), then.

**Comment by FlorianLudwig** [comment]
With emulation i meant this: https://developers.google.com/web/tools/chrome-devtools/device-mode

**Comment by sneas** [comment]
Ah, I see it now. I'm going to see what could be done. Thanks!

**Comment by kevupton** [comment]
any news on this one?

**Comment by sneas** [comment]
Hi @kevupton, thank you for enquiring. I'll do my best to provide a fix this (or at least the next) week.

**Comment by sneas** [comment]
@kevupton, @FlorianLudwig **v2.4.2** provides a quick fix for the _touchmove_ event on mobile browsers. I'm still not entirely satisfied with bounce scroll behaviour:

![Kapture 2020-10-07 at 09 56 21](https://user-images.githubusercontent.com/144651/95306020-17edce00-0887-11eb-988f-e31af9c9de00.gif)

I'm going to keep this issue opened until I find a good enough solution for that.

**Comment by kevupton** [comment]
ahhh yeh ok, keep up the good work, hard to find a decent one of these 😄
