### ISSUE TITLE
Using a png img as the handle

### ISSUE THREAD

**Issue by nicoladj77** [sneas/img-comparison-slider#118]
I have been trying to use an image png for the handle, without luck, while with an SVG element there are no issues. 
My setup is very simple, for exmpla this works

	<img-comparison-slider handle="true">
		<svg slot="handle" xmlns="http://www.w3.org/2000/svg" width="60" height="654" viewBox="0 0 60 654" version="1.1"><path d="M 28.347 267.750 C 27.253 279.240, 27.256 374.679, 28.351 387.349 C 28.865 393.299, 29.563 396.837, 30.116 396.284 C 33.658 392.742, 33.491 259, 29.945 259 C 29.524 259, 28.805 262.938, 28.347 267.750" stroke="none" fill="#fcfcd1" fill-rule="evenodd"/><path d="M 28.151 71.581 C 16.079 124.151, 16.462 544.980, 28.619 586.250 C 30.978 594.257, 33.923 576.936, 35.974 543 C 44.355 404.283, 40.662 82.229, 30.531 68.374 C 29.440 66.881, 29.136 67.290, 28.151 71.581 M 28.347 267.750 C 27.253 279.240, 27.256 374.679, 28.351 387.349 C 28.865 393.299, 29.563 396.837, 30.116 396.284 C 33.658 392.742, 33.491 259, 29.945 259 C 29.524 259, 28.805 262.938, 28.347 267.750" stroke="none" fill="#fcf20b" fill-rule="evenodd"/></svg>
		<img slot="first" src="/wp-content/themes/10up-theme/dist/images/comparison-image2.jpg" alt="" />
		<img slot="second" src="/wp-content/themes/10up-theme/dist/images/comparison-image1.jpg" alt="" />
	</img-comparison-slider>

but if I remove the SVG and use an image instead, even an image loading an svg, the handle doesn't appear

**Comment by sneas** [comment]
Hi @nicoladj77 , I have just succeeded using a PNG handle with the below example

```html
<img-comparison-slider>
  <img
    slot="first"
    width="100%"
    src="images/leaves.webp"
  />
  <img
    slot="second"
    width="100%"
    src="images/leaves-blurred.webp"
  />
  <img src="images/left-right.webp" slot="handle" width="50" />
</img-comparison-slider>
```

Can you show the non-working example?

**Comment by sneas** [comment]
I'm closing this issue for now. Feel free to reopen it in case of any problem with using a PNG image as a custom handle.
