### ISSUE TITLE
Having trouble implementing vertical direction based on examples

### ISSUE THREAD

**Issue by hansen-ri** [sneas/img-comparison-slider#119]
I'm making a Vue3 app that uses the standard/default version of the img-comparison-slider just fine, but I can't figure out how to get any of the other options to work, specifically the 'direction="vertical"' setting. Have I forgotten to import something important if I only used the npm install CLI prompt?

**Comment by sneas** [comment]
Hi @hansen-ri. I've just tried it out, and it seems like you found a bug. I'm going to address it in the upcoming days.
