### ISSUE TITLE
Change slider position via JS

### ISSUE THREAD

**Issue by f3bruary** [sneas/img-comparison-slider#120]
I would like to be able to set the slider position via JavaScript. Example use case:

1. Click a button that moves the slider.
2. Use the intersection observer api to move the slider as you scroll up/down.

**Comment by sneas** [comment]
Hi, you can change the slider position by updating it's `value` prop.

A quick example:

```js
document.getElementsByTagName('img-comparison-slider')[0].value = 60; // Set slider position to 60%
```

**Comment by wpinfusion** [comment]
damn, I actually tried that using setAttribute. Although the value changed, the slider didn't. But you method works fine indeed. Thanks a lot.

**Comment by f3bruary** [comment]
damn, I actually tried that using setAttribute. Although the value changed, the slider didn't. But you method works fine indeed. Thanks a lot.

**Comment by sneas** [comment]
This is misleading, indeed. I haven't thought of the `setAttribute` use case.

**Comment by f3bruary** [comment]
I'm also trying the same with querySelector instead of getElementsByTagName, but that doesn't work either.
e.g:

```html
<div id="test">
  <img-comparison-slider id="comparison-wrapper" value="0">
  ...
  </img-comparison-slider id="comparison-wrapper">
</div>
```

```js
const wrapper = document.querySelector('#test #comparison-wrapper');
wrapper[0].value = 10;
```

I'm sure I'm doing something wrong, but I don't see what exactly.

**Comment by sneas** [comment]
You don't have to take `[0]`. `wrapper.value = 10` should be enough.

Also, there is no need to select `#test #comparison-wrapper` . `#comparison-wrapper` should be enough, unless you have multiple elements with the same `comparison-wrapper` IDs.

**Comment by f3bruary** [comment]
Thanks I got it working.
