### ISSUE TITLE
Feature Request: Have Labels fade-in on hover

### ISSUE THREAD

**Issue by felkeM** [sneas/img-comparison-slider#121]
Is there a way for the labels to fade in on hover? 

Example: https://zurb.com/playground/twentytwenty

**Comment by sneas** [comment]
This component is quite customizable with the help of CSS, HTML, and JS. Here is how to make it act somewhat like twentytwenty from your example https://codepen.io/sneas/pen/WNLYaQm. Is this something you were looking for?
