### ISSUE TITLE
Programmatically slide the handle

### ISSUE THREAD

**Issue by fostimus** [sneas/img-comparison-slider#124]
In React world, we can use a components methods via a ref. A ref that has a way to programmatically move the handle would be awesome, right now I'm getting the position via the `onSlide` prop and setting back to what I want in the `value` prop. Which is causing more renders than needed :/

**Comment by sneas** [comment]
Hi Derek, the ref issue is fixed. Here is how you can use ref in case of Typescript

```tsx
import { useRef } from 'react';
import { HTMLImgComparisonSliderElement, ImgComparisonSlider } from '@img-comparison-slider/react';

function App() {
  const sliderRef = useRef<HTMLImgComparisonSliderElement>(null);

  return (
    <ImgComparisonSlider ref={sliderRef}>
      <img slot="first" src="https://img-comparison-slider.sneas.io/demo/images/before.webp" />
      <img slot="second" src="https://img-comparison-slider.sneas.io/demo/images/after.webp" />
    </ImgComparisonSlider>
  );
}

export default App;
```

Feel free to reopen the issue or create a new one in case of any problem.
