### ISSUE TITLE
Text gets selected on Safari

### ISSUE THREAD

**Issue by legendofmi** [sneas/img-comparison-slider#127]
When using my Magic Keyboard trackpad on iPadOS Safari, the text and other content get selected while I'm dragging the handle.
https://github.com/sneas/img-comparison-slider/assets/94787966/4bbc7ac8-5139-4a90-ba52-c10dea5f70ea

**Comment by sneas** [comment]
Thank you for reporting this bug. I'll have a look.

**Comment by legendofmi** [comment]
Thanks for the quick fix! I can confirm it’s now working perfectly :)
