### ISSUE TITLE
ReferenceError: HTMLElement not defined during Vite-SSG build with img-comparison-slider

### ISSUE THREAD

**Issue by ademtonay** [sneas/img-comparison-slider#129]
### Issue Summary:

I am encountering an issue during the build process of my Vite-SSG project. The error is related to the img-comparison-slider module, and it appears to be a ReferenceError: HTMLElement is not defined problem.

Environment:

* Node.js version: 18.18.0
* Vite version: 5.0.3
* Operating System: [mac OS]

### Steps to Reproduce:

1. Run vite-ssg build on a project that includes the img-comparison-slider module.
2. Observe the error mentioned in the issue description

### Error Details:
```csharp
[vite-ssg] Build for client...
vite v5.0.3 building for production...
...
ReferenceError: HTMLElement is not defined
    at node_modules/.pnpm/img-comparison-slider@8.0.5/node_modules/img-comparison-slider/dist/index.js:1:4062

```

### Additional Information:

* The project is using Vite-SSG.
* The img-comparison-slider module version is 8.0.5.

### Expected Behavior:

The build process should complete without encountering a ReferenceError related to HTMLElement.

**Comment by sneas** [comment]
Thank you for opening the issue, Adem. I will fix it in the upcoming days.

**Comment by ademtonay** [comment]
Thanks. Good job!
