### ISSUE TITLE
js / css (scss) version

### ISSUE THREAD

**Issue by nhaberl** [sneas/img-comparison-slider#13]
is there a chance just to download a simple css / js version also for using in a simple website ?

**Comment by sneas** [comment]
Hi Norbert, unfortunately, there is no way to distribute the component as a single file. At least I couldn't figure out how to do that with Stencil (the framework behind this component). But you might achieve what is needed by following these steps:

1. Run `npm pack img-comparison-slider` to download the componenent's package
2. Put the `package/dist` contents in a public folder.
3. Include `component.js` to the page in an good old-fashioned way:

```html
<script src="package/dist/component/component.js"></script>
```
The script downloads and includes the rest of the files, and renders the component.

However, if you have a chance, I'd recommend to include the script in the following way:

```html
<script type="module" src="package/dist/component/component.esm.js"></script>
<script nomodule="" src="package/dist/component/component.js"></script>
```

By including the script the above way, we let modern browsers (the overwhelming majority of users) to use a much leaner version of the script (~7kb in total) VS the polyfilled version prepared for ancient browsers (which is ~40kb in total).

I hope this helps.

**Comment by sneas** [comment]
The library is now distributed as a single JS and single CSS file. Installation instructions https://github.com/sneas/img-comparison-slider#html are available.
