### ISSUE TITLE
🪲 Blue line appeares when selecting the slider.

### ISSUE THREAD

**Issue by sanketkheni01** [sneas/img-comparison-slider#130]
![image](https://github.com/sneas/img-comparison-slider/assets/68942390/3b63a379-732d-4ab9-a43b-5afb068dccf6)

How to reproduce:-
Devices :-  only mobile

When selecting the slider, a blue line appears at the bottom.

**Comment by sneas** [comment]
Oh, I'm very sorry for the late response. This issue somehow went below my radar. You can get rid of the blue line by disabling the :focus outline on the component:

```css
img-comparison-slider {
  outline: none;
}
```

Just fyi, the focus outline serves the usability purpose, as it indicates when the element is selected and can be controlled by the keyboard.
