### ISSUE TITLE
Use custom divider

### ISSUE THREAD

**Issue by squidiw** [sneas/img-comparison-slider#131]
Hi, wanted to know if there’s a way I can use a custom divider ? For example an svg? 

Currently the options are to modify the existing divider but not change it entirely like how the handle can be changed by using slot=handle

**Comment by sneas** [comment]
There is no option to use a custom divider at the moment. What kind of divider would you like to use?

**Comment by squidiw** [comment]
Something like this from a generator - https://kovart.github.io/dashed-border-generator/
<img width="1163" alt="Screenshot 2023-12-18 at 8 55 41 AM" src="https://github.com/sneas/img-comparison-slider/assets/39523709/56c29aa3-da75-4111-b278-2fc6523919f7">

And this is a png of it 
![Line_130](https://github.com/sneas/img-comparison-slider/assets/39523709/8d9012c0-a0f2-43f3-9cc1-2d83bddea652)

**Comment by squidiw** [comment]
In the future if anyone wants to change the divider, what I ended up doing is,
`const slider =  document.querySelector('img-comparison-slider');
  if(slider){
    setTimeout(() => {
      let sliderDivider = slider.shadowRoot;
      let styleSheet = document.createElement('style');
      sliderDivider.insertBefore(styleSheet, sliderDivider.children[0]);

      let rules = [
        `.divider{border:none;width:2px!important;}`,
        `.divider:after{border:none!important;width:2px;background-repeat:repeat-y;background-image:url("data:image/png;base64,........");}`
      ]
      
      rules.forEach((rule, index) => {
           styleSheet.sheet.insertRule(rule, index);
      })
    }, 1000);
  }`
