### ISSUE TITLE
Responsive container, image cover option

### ISSUE THREAD

**Issue by robozb** [sneas/img-comparison-slider#134]
Can I specify the height relative to the viewport (e.g., 33vh) while keeping the width at 100%, but the image won't be distorted, maintaining the original proportions, so it covers the image?

**Comment by sneas** [comment]
Hi Roboz!

`img-comparison-slider` follows web standards, which makes the slider extremely flexible. You can do whatever you want with the images as long as it is supported by HTML, CSS, and JS.

For example:

```
<style>
  .image {
    width: 100%;
    max-height: 33vh;
  }
</style>
<img-comparison-slider>
  <img slot="first" src="image1.jpg" class="image" />
  <img slot="first" src="image1.jpg" class="image" />
</img-comparison-slider>
```

You may even wrap your images with any tag for better flexibility, as this example suggests https://img-comparison-slider.sneas.io/examples.html#before-and-after-labels

If you are still stuck on anything, feel free to let me know, and I'll be glad to help.

**Comment by sneas** [comment]
Hi Roboz, I'm going to close this issue for now. If you feel that I didn't help you with it, then feel free to reopen it, and elaborate on the problem so I can better understand it.

Also, feel free to open a new issue if you have some other problems.
