### ISSUE TITLE
Way to disable blue border

### ISSUE THREAD

**Issue by bddicken** [sneas/img-comparison-slider#136]
Hey, thanks for making this awesome tool! 

I cannot seem to find a way to disable the thin blue border that appears when you click on the img-comparison-slider. 

<img width="117" alt="Screenshot 2024-03-04 at 10 57 39 AM" src="https://github.com/sneas/img-comparison-slider/assets/1181638/92065587-69bd-4c6d-9de6-8bd66c3b13a1">

Would be really great if this could be disabled! I tried to set some CSS to get rid of it, such as `user-select: none;` and `-webkit-tap-highlight-color:transparent;` but to no avail. Any tips on how to get rid of this would be wonderful!

**Comment by sneas** [comment]
Hey, just set

```html
img-comparison-slider {
  outline: none;
}
```

in CSS.
