### ISSUE TITLE
Is it possible to refresh the slider after initial page load?

### ISSUE THREAD

**Issue by mably** [sneas/img-comparison-slider#140]
In our case we are trying to inject the `<img-comparison-slider>` element dynamically into the page DOM via Ajax.

Thanks for your help.

**Comment by sneas** [comment]
Can you please elaborate on the "refresh" part?

**Comment by mably** [comment]
Thanks for your quick answer.

Practically, some Ajax command is trying to render my <img-comparison-slider> code into a CKEditor 5 instance.

The correct HTML is injected into the page but not rendered properly as I guess ICS is only doing its things on page load.

I would like to be able to redo it after that Ajax command is executed.

**Comment by sneas** [comment]
Hence, it's a web component that should work for any newly injected `<img-comparison-slider>` tag. As soon as you have the necessary JS included. If it is not happening, there might be a bug. Before assuming it's a bug, can you ensure you have the needed JS on the page?

**Comment by mably** [comment]
Indeed, I will check that, thanks for your help.

**Comment by mably** [comment]
You were right, Image Comparison Slider javascript was not loaded.

Here is the related Drupal issue for those interested: https://www.drupal.org/project/drupal/issues/3072317
