### ISSUE TITLE
only one image is displayed. Can it be set so that when there is only one image

### ISSUE THREAD

**Issue by xiaoshangmin** [sneas/img-comparison-slider#143]
Currently, only one image is displayed. Can it be set so that when there is only one image, the other side is displayed as blank by default?

**Comment by sneas** [comment]
This component is quite flexible regarding images. You can use arbitrary HTML instead of images. For example:

```html
<img-comparison-slider>
  <img slot="first" src="./image.1" />
  <div slot="second"></div> <!-- 👈 this can be anything. Your imaginations is restricted by your knowledge of HTML, CSS, and Javascript -->
</img-comparison-slider>
```
