### ISSUE TITLE
nuxt3 not working

### ISSUE THREAD

**Issue by xiaoshangmin** [sneas/img-comparison-slider#144]
```
<script setup> 
import { ImgComparisonSlider } from '@img-comparison-slider/vue';
</script>
```
![image](https://github.com/user-attachments/assets/a600200c-914d-4b47-b150-cbeda5f1d4ed)

**Comment by sneas** [comment]
I am asking for my piece of mind. Do you have `@img-comparison-slider/vue` folder in your `node_modules`?

**Comment by xiaoshangmin** [comment]
> I am asking for my piece of mind. Do you have `@img-comparison-slider/vue` folder in your `node_modules`?

![image](https://github.com/user-attachments/assets/37151b4f-6ae9-4b17-bc9f-319ad1e053e0)

I am using nuxt 3.12 version, will it have any impact

**Comment by sneas** [comment]
You are showing a package with the name `img-comparison-slider`. You need to install `@img-comparison-slider/vue` if you don't have it yet.

**Comment by xiaoshangmin** [comment]
thanks
 I used the wrong package
