### ISSUE TITLE
Divider Line Extends Past Images

### ISSUE THREAD

**Issue by rainwilds** [sneas/img-comparison-slider#20]
Hi there,

Thank you for the great JS comparison slider.

I have an issue the shows the divider line extending past the before/after images. I have a live demo of the issue at the link below:

[https://behive.co/beforeafter1/](https://behive.co/beforeafter1/)

Any help would be much appreciated

Let me know also how I can donate towards the project.

Thanks,
David

**Comment by sneas** [comment]
Hi David, thank you for creating the issue and providing the example 👍

As a workaround, for now, you can set `line-height: 0` for the `img-comparison-slider` element.

Something like:

```css
img-comparison-slider {
  line-height: 0;
}
```

Soon (hopefully, at the end of this week), I'll provide a patch fixing the problem on the component's level, so you and other users won't have to deal with that on their end.

**Comment by rainwilds** [comment]
Thank you Dmitry for looking into this.

It seems like I cannot adjust the styling for the img-comparison-slider element by adjusting the global CSS or inline. It just doesn’t apply the style to the rendered img-comparison-slider element.

If I place the line-height code after after the DOM has loaded it works, but not beforehand.

I could try JS but will wait to see if you get chance to update the code.

Thank you,
David

**Comment by rainwilds** [comment]
Hi Dmitry,

Sorry ignore that previous email. I had server caching on making an old stylesheet load. It works now.

Thanks,
David
