### ISSUE TITLE
Not working with dynamic images, there is no way i can reinitialize it after dynamic images load

### ISSUE THREAD

**Issue by techtic-maulik** [sneas/img-comparison-slider#21]

**Comment by sneas** [comment]
Could you please describe the use case?

Do you update `src` attribute of an image? Or do you add a new image with `appendChild`?

I need more details to better help you.

**Comment by techtic-maulik** [comment]
```
<ng-template #imageComparison let-modal>
  <div class="modal-header">
    <h4 class="modal-title" id="modal-basic-title">Before After</h4>
    <button type="button" class="close" aria-label="Close" (click)="modal.dismiss('Cross click')">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body" style="padding :2rem;">
    <img-comparison-slider>
  	  <img slot="before" src="{{imgBaseUrl}}/{{beforImage}}">
  	  <img slot="after" src="{{imgBaseUrl}}/{{afterImage}}">
  	   <img slot="handle" class="custom-handle" src="{{ markersLogo }}/chevron-handle.svg">
  	</img-comparison-slider>
  </div>

</ng-template>
```
I am updating the image src  like mention in model

**Comment by sneas** [comment]
Hi Maulik, I was trying to reproduce the issue but failed. The dynamic images work as expected for me. I created the working example https://github.com/sneas/example-img-comparison-slider-angular/blob/dynamically-change-images/src/app/app.component.html (the name of the branch is `dynamically-change-images`).

I need your help. Could you please reproduce the issue in the example app and create the PR into https://github.com/sneas/example-img-comparison-slider-angular.

Thank you!

**Comment by sneas** [comment]
Hi, the slider is now exports `reset` method. Please consider this example https://github.com/sneas/example-img-comparison-slider-angular/blob/d0511c031b85b6210a24f511e812861aacc688f3/src/app/app.component.ts#L16.

**Comment by sneas** [comment]
Slider position could be set via `value` property. https://github.com/sneas/img-comparison-slider#supported-attributes
