### ISSUE TITLE
Is it possible to add a custom handler icon?

### ISSUE THREAD

**Issue by lucianourgal** [sneas/img-comparison-slider#22]
I'm currently using React and there is a .svg or React component I'd like to use as a handler.

**Comment by sneas** [comment]
Hi @lucianourgal, it is possible to use .svg. The following example does exactly that: https://sneas.github.io/img-comparison-slider/#custom-handle

As for a react component (or any other random HTML tag), I'm considering that as a new feature for the library which will be available in the future version (I can't give you any estimates on the release date).

**Comment by lucianourgal** [comment]
Thanks for the quick answer @sneas !

I'll try that.
