### ISSUE TITLE
Bundling with webpack

### ISSUE THREAD

**Issue by andreyvolokitin** [sneas/img-comparison-slider#27]
The code in the `dist` folder contains dynamic `import()` which causes webpack to generate dynamically loaded chunks when importing `img-comparison-slider/dist/component/component.esm.js`, which is pretty confusing. 

Is there a way to bundle it in a "usual" way, with a single dist file, or source entry file allowing to bundle into the single file?

**Comment by sneas** [comment]
Hi Andrey, I can look into it next week. To be honest, I also didn’t feel comfortable with the approach and I have foreseen concerns from the lib users. But reading through Stencil docs and trying the lib in various environments boosted me with some confidence towards the dynamically loaded esm modules.

I’d expect Webpack to bundle the lib in a single file, but I might be wrong. Anyway, I’ll keep you updated regarding this issue.

**Comment by andreyvolokitin** [comment]
Webpack will bundle it in 3 separate things:

- it will include the main "boilerplate" code into the main bundle (I guess this is a stencil base code). This "base code" contains dynamic `import()`...
- ...and because of this it will create 2 dynamically loaded chunks, "regular", for System.js. In reality only one is used (with webpack it is a "regular" chunk, System.js chunk is just left unused)

It might not be a big problem apart from confusion and slight deviation from user expectations (i.e. all JS is loaded right away when you don't tell it to load dynamically), but it was quite confusing. 

I'm not sure if webpack allows forcing dynamic imports to be included into a single bundle instead of loading dynamically, but I think this is also not a solution, because there're 2 chunks generated, and for that I suspect you can't tell webpack which one is to force for inclusion (if this is at all possible)

**Comment by sneas** [comment]
Hi Andrey, the new major version of the library (4.x) has been released. The library has been rewritten with vanilla JS (TS) and the build process is now using Webpack. This has provided full control over the library and bundling. So now the library is distributed as a single JS file. Source maps and typings are also included.
