### ISSUE TITLE
Before and After Images are in reverse order

### ISSUE THREAD

**Issue by yagudaev** [sneas/img-comparison-slider#33]
This screenshot is straight from the demo:

![Screen Shot 2021-06-16 at 2 18 30 PM](https://user-images.githubusercontent.com/1386966/122295235-d13c8300-cead-11eb-90be-68bd208c9c52.png)

The dog shows up on the left-hand side as the "after" picture and the cat shows up on the right-hand side as the "before" picture. This is really confusing. I expect the order to be reversed, first show a before and then show an after picture.

To make it clear to users on the demo site, can we use the same image just with a filter? Say a cat image with Sepia filter? Or a day then night image as an example.

If you look at https://www.remove.bg/ you will see what I mean. Left side is always before and right side is after.

**Comment by sneas** [comment]
That's a good one! I'll fix it.

**Comment by sneas** [comment]
Hi Michael. The library is slightly refactored based on your feedback. Now it uses "first" and "second" slots instead of "before" and "after". Because "before" and "after" don't cover all the possible use cases. RIght now the "first" slot rendered on the left hand, and the "second" slot is on the right. The library renders slots from left to right also on `dir="rtl"`. Which I consider as an accessibility issue that has to be addressed in the future.

**Comment by yagudaev** [comment]
This is amazing! Thank you so much. I'm already using the latest library now on production for [1touch.photo](1touch.photo), it works great :). 👍

**Comment by sneas** [comment]
Hi Michael, I'd recommend rendering all the 3 sets of before-after photos and show/hide them on tab clicks. This can help to overcome the instantaneous stretch effect on image set change:
![Kapture 2021-06-23 at 08 50 57](https://user-images.githubusercontent.com/144651/123050096-992ec600-d400-11eb-8cff-285dcae39587.gif)

If I were you, I'd also be tempted to remove or change the default onFocus outline from the slider.

The default outlook (chrome):
![image](https://user-images.githubusercontent.com/144651/123050722-4acdf700-d401-11eb-855c-56d813f41282.png)

This how it looks like with `img-comparison-slider { outline: none; }`:
![image](https://user-images.githubusercontent.com/144651/123050953-88328480-d401-11eb-9a58-e110b870db04.png)

This is how it may look with slight customization `img-comparison-slider:focus { outline: rgba(59, 130, 246, 0.5) dotted 1px }`
![image](https://user-images.githubusercontent.com/144651/123051613-4524e100-d402-11eb-8ae1-960a1c1f9c94.png)

The overall impression of the website is awesome!

Please feel free to let me know of any issues with the library. Your feedback is very important.
