### ISSUE TITLE
Offset divider?

### ISSUE THREAD

**Issue by brianyuen** [sneas/img-comparison-slider#40]
Hi, thank you for this! Is there a way to offset the divider on load? Currently it sits at the center (50%), but I would like it to be a bit over to the right on load. (20%).

Thank you!

**Comment by sneas** [comment]
Hi Brian, this is the feature I plan on delivering in the upcoming 2 weeks. I'll keep you posted.

**Comment by sneas** [comment]
From now on, the component supports `value` property https://github.com/sneas/img-comparison-slider#supported-attributes

Thank you for your feedback!
