### ISSUE TITLE
Before after img height

### ISSUE THREAD

**Issue by aimilin** [sneas/img-comparison-slider#42]
I have a small suggestion  for this plug-in unit.
if I upload two images with diffrent width and height ,  the style will be like this:
![image](https://user-images.githubusercontent.com/5086089/124890835-03ec1e00-e00b-11eb-87ad-fbfeee14eaea.png)
Could you help to update the two picture's or div's as same height.

**Comment by aimilin** [comment]
I'm try to reset style out shadow-root, but I can't do it , reset style doesn't work.

**Comment by sneas** [comment]
Hi, to mitigate difference between image sizes, I’d suggest to use a combination of ‘background-image’ and ‘background-size: cover’. It’s not necessarily needed to use ‘img’ tag. Feel free to use any tag for images.

The component is keeping it’s styles in shadow dom, so there is no way to tweak component’s styles, you’re right. But you have full capacity of HTML, CSS and JS at your disposal to fit images as needed.

**Comment by sneas** [comment]
I’m sorry I’m away from my computer for upcoming days. I’ll think of an example of how to deal with a situation like yours.

**Comment by aimilin** [comment]
I got it,  I can set style for img or div, It's very powerful and perfect!!
Thank you very much!

**Comment by aimilin** [comment]
If it does not affect other functions，I think this will be ok to add below style for .first div. (*right, bottom and width, height*)
Any pictures of different sizes can fit it.
when my customer to fixt some machine, he will upload a picture before he fixt it, and he also need upload a picture after he fixt it,  I don't know whitch size picture uplod by my customer , so if these two pictures are diffrent size, my question was appeared.
I tried to use the method you provided, there will still be a little problem with handle-container
.first {
	position: absolute;
	left: 0;
	top: 0;
        right:0;
        bottom:0;
	line-height: normal;
	font-size: 100%;
	--exposure: 50%;
	--transition-time: 0ms;
	transform: translateX(calc(var(--exposure) * -1));
	transition: transform var(--transition-time);


}

.first .first-overlay-container {
	position: relative;
	transform: translateX(var(--exposure));
	transition: transform var(--transition-time);
        width: 100%;
        height: 100%
}

.first .first-overlay {
	overflow: hidden;
        width: 100%;
        height: 100%
}

**Comment by sneas** [comment]
Hi @aimilin,

This is the comment I gave in another issue, but it can help you to solve the problem of images of different sizes https://github.com/sneas/img-comparison-slider/issues/58#issuecomment-961068689

Thank you for your patience and feel free to reopen this issue if necessary.
