### ISSUE TITLE
Resize issue in frame

### ISSUE THREAD

**Issue by bobsyourgrannie** [sneas/img-comparison-slider#43]
HI sneas, loving the slider. We have run into an issue when we are using the slider within a resizable frame. We have a split-screen package we are using and the slider is in the left panel of the split-screen. This image shows the correct positioning of the two images.

![image](https://user-images.githubusercontent.com/22720724/125214868-b4546d80-e2fc-11eb-94f3-b2368b075b34.png)

Now, if I drag the width of this frame, the photo slider goes out of whack. In the below image after I have resized the split-screen panel, you can see that the slider's left image does not respond correctly. The right image resizes correctly however. The drag handle also does not correspond with the mouse position anymore - it is to the left or right of where it thinks it is.

![image](https://user-images.githubusercontent.com/22720724/125214941-07c6bb80-e2fd-11eb-9675-e5eb99a4c0e6.png)

When I drag the split-screen panel to the right to expand the slider, I get this:

![image](https://user-images.githubusercontent.com/22720724/125215139-d8fd1500-e2fd-11eb-8776-387d114dc6e9.png)

The instant that I drag the browser window width, this all corrects itself as it is obviously running your refresh code. I am thinking that the easiest solution from your end might be to just expose a refresh function and we can send that request to the slider as we resize the split screen, or alternatively you also monitor physical size changes of the slider somehow.

I presume this is the function that is doing the resize work:
![image](https://user-images.githubusercontent.com/22720724/125215174-f4682000-e2fd-11eb-8305-9d5935bbbe25.png)

**Comment by sneas** [comment]
Hi, @bobsyourgrannie. I'd be happy to help you with the issue. I see the fact that the library is acting inappropriately on the frame resize as a bug. And I'd rather fix it some other way than exposing the `reset` function.

The component is supposed to take care of its dimensions changes by utilizing `ResizeObserver` https://github.com/sneas/img-comparison-slider/blob/master/src/index.ts#L77-L78 . It's relatively new code, so first of all, I'm wondering, which version of the library are you using? And if it's not v7.1.0, can I ask you to update the version in your packages?

Also, I'm wondering, have you tried to give your images relative width? I.e. `100%` as examples do (https://sneas.github.io/img-comparison-slider/). This may help.

I may be wrong, but the way I see the problem right now (given all the information I have), it seems like the solution could also be not on the library's end at all. Just for the sake of experiment, could you try to output the first image only without the library? For example, replacing 

```html
<img-comparison-slider>
  <img slot="first" ... />
  <img slot="second" ... />
</img-comparison-slider>
```

with

```html
<img slot="first" ... />
````

This will output the first image only. Are you satisfied with the image outlook and dimensions after dragging the split-screen? If no, then probably, fixing that single image outlook (preferably with CSS only), will also fix the problem with the component.

I'd be happy to reproduce the problem on some public repo or sandbox, to help you with this problem. But unfortunately, I do have limited screen time these days. If you can help me to shed more light on the problem, I'll do my best to help you and other users in the best possible way.

**Comment by bobsyourgrannie** [comment]
My apologies sneas, we were using version 3 of the slider. I have updated to 7 and changed the Angular import method as described and it works fine. Looks like the new ResizeObserver is working a charm!
