### ISSUE TITLE
How to trigger the comparison on mouse hover not on click?

### ISSUE THREAD

**Issue by ImSolitude** [sneas/img-comparison-slider#50]
Is there any way to do that currently?
Thanks

**Comment by sneas** [comment]
No, but I'm going to provide it as a new feature.

**Comment by TangoPJ** [comment]
I had the same question, thank you :)

**Comment by TangoPJ** [comment]
I'm using this slider in my project, it's really awesome and I have a question - Can I set the time after which the border between photos returns to the center?

**Comment by sneas** [comment]
> I had the same question, thank you :)

I’m almost finished with this feature, but it needs a bit more work. Going to provide it this weekend.

**Comment by sneas** [comment]
> I'm using this slider in my project, it's really awesome and I have a question - Can I set the time after which the border between photos returns to the center?

Thank you for your kind words, @TangoPJ .

Unfortunately, you’ll need ‘onChange’ event to achieve that. It is not yet implemented. I’ll do my best to provide it, but I can’t promise fast result. Perhaps, 2-3 weeks.

I’ll create separate GH issue to track your request.

**Comment by TangoPJ** [comment]
> I’ll create separate GH issue to track your request.

Thank you for the answer :)
