### ISSUE TITLE
Can't register img-comparison-slider in my Vue2.js component

### ISSUE THREAD

**Issue by TangoPJ** [sneas/img-comparison-slider#52]
The slider is working correctly, but my tests show me the error:

![ksnip_20210903-062958](https://user-images.githubusercontent.com/64611024/131960535-b1f28ee2-af5d-47ae-abff-6ec47f55d875.png)

How can I register the slider as a local component?

Thank you in advance!

**Comment by sneas** [comment]
The setup steps are described in this doc https://github.com/sneas/img-comparison-slider/blob/master/docs/installation/vue.md
