### ISSUE TITLE
Horizontal divider for image comparison

### ISSUE THREAD

**Issue by ravinsharma7** [sneas/img-comparison-slider#56]
Hi 

Is there any setting to show a horizontal divider. This would be useful in comparing photo that are in the medical field(faces etc). Or could I do this from the code itself.

I like the library by the way.

**Comment by sneas** [comment]
There is no such an option yet. But I'll consider it as a good enhancement. I can't promise this feature to be delivered fast, thought. But let's keep this issue opened.

**Comment by LukeTowers** [comment]
I'd also be interested in such a feature, any pointers for where to get started with it if I have some time to take a look at implementing it in a PR?

**Comment by sneas** [comment]
Hey @LukeTowers, this will be great! The starting point is quite straightforward: `clone`, `npm install`, `npm start`. The component's internals could be found in `src/index.ts` and `src/styles.scss`. Feel free to let me know if you have any questions.
