### ISSUE TITLE
Unable to setup with vue-cli (vue 3)

### ISSUE THREAD

**Issue by quinncheong** [sneas/img-comparison-slider#57]
Hi,

Appreciate the library. While I was setting it up with vue-cli (using vue v3.0.0), the app was returning an "Uncaught Reference Error: Vue is not defined.". I looked into it and traced the error back to the index.browser.js file. 

I tried to rectify it by 'requiring' vue at the start of the file. I was able to remove the error and run the app, but the img slider shows the image vertically stacked on top of each other.

Not sure if this is an issue or I'm operating the library a little wrong.

Thanks for the help.

**Comment by sneas** [comment]
@quinncheong, thank you for opening the issue. I was unaware of the fact it wasn't working, thus this issue was a great contribution to the project 👍

Also thank you for helping out @paulwesner to resolve his problem 💪

Now the library behavior should be aligned with the documentation.

**Comment by quinncheong** [comment]
Thanks for the help! 

Appreciate everything that you've done. I'm happy to have contributed in a small way. Cheers!
