### ISSUE TITLE
Allow better styles customization

### ISSUE THREAD

**Issue by jahirfiquitiva** [sneas/img-comparison-slider#58]
Hello

I would like to be able to make each item inside the slider have custom styles... for example... having height of 100% so they fill the parent height... instead of showing the other image behind (which doesn't look good for images with different dimensions)

Here's an example of the issue I'm facing ... what can I do to make it better?

![Shot 2021-11-03 at 02-30-17](https://user-images.githubusercontent.com/10360816/140023134-4e3e2740-3a37-4b45-aede-573e6610d2c6.gif)

**Comment by sneas** [comment]
Hi @jahirfiquitiva. Thank you for the issue. I have just published a fix for the library which allows customization of each image with all the power of CSS and HTML. Basically, a slot shouldn't necessarily be an image. It can be any HTML tag and can contain any other tags inside. For example in your case, you can do something like

```html
<img-comparison-slider>
  <div slot="first" style="height: 100%; any-other-style-which-can-help">
    <img src="smaller-image.jpg" />
  </div>
  <img slot="second" src="larger-image.jpg" />
</img-comparison-slider>
```
