### ISSUE TITLE
After image is covering component's on-focus outline

### ISSUE THREAD

**Issue by sneas** [sneas/img-comparison-slider#6]
![image](https://user-images.githubusercontent.com/144651/83547418-79311980-a502-11ea-99be-aeff83b1a0b2.png)

**Comment by sneas** [comment]
Fixed with e8e5eeb1c659ad14bb5ded587baea6e68b358ba6

**Comment by filipchrapek** [comment]
Hi @sneas!
I still have similar issue. Adding `outline: none` seems to help.

![image](https://user-images.githubusercontent.com/19151210/147577015-6dfe04e7-3e14-48c5-911d-852fe1db47b4.png)
