### ISSUE TITLE
How to use with Nuxt 2?

### ISSUE THREAD

**Issue by Tuginho** [sneas/img-comparison-slider#61]
I've added it in my nuxt.config.js to the plugins like this:
`    { src: '~/plugins/img-comparison-slider.js', mode: 'client' },`

But dont know exactly what to put in my img-comparison-slider.js file.
That way it's not working for me:

```
import Vue from 'vue'
import ImgComparisonSlider from "img-comparison-slider"
// Tell Vue that the web component is present.
Vue.config.ignoredElements = [/img-comparison-slider/];
Vue.use(ImgComparisonSlider);
```

Thanks for your help!

**Comment by sneas** [comment]
Hi, this readme explains how to use the component with Vue2 framework https://github.com/sneas/img-comparison-slider/blob/master/docs/installation/vue.md

Have you already tried to install the component this way?
