### ISSUE TITLE
[custom handler] Issue with hover state

### ISSUE THREAD

**Issue by filipchrapek** [sneas/img-comparison-slider#63]
I added custom SVG handler and somehow I have trouble with simple `cursor: pointer` on hover. I tried with default handler and it doesn't seem to work either. What am I doing wrong?

**Comment by sneas** [comment]
Seems like it's a bit tricky to add `cursor: pointer` to an SVG container. It's not because of this lib, it's a general problem https://stackoverflow.com/questions/26672936/cursor-pointer-on-svg-element-is-not-working

**Comment by filipchrapek** [comment]
Hmm, that is tricky indeed - thank you for the tip.

By why can't I access e.g. `.handle` and use hover there? It doesn't seem to work either.
