### ISSUE TITLE
Default divider position cannot be set

### ISSUE THREAD

**Issue by LukeTowers** [sneas/img-comparison-slider#72]
This can be replicated on the usage example page: https://img-comparison-slider.sneas.io/examples.html#position

Setting a `value=""` property on the component is not taking effect.

**Comment by sneas** [comment]
Hi Luke. Thank you for raising the issue 👍 It has just been fixed. Have a great day, mate.

**Comment by LukeTowers** [comment]
Thanks for fixing it quickly @sneas!

**Comment by mkariti** [comment]
Hi, Ive installed the latest version 7.5.2 and still experiencing this issue.
Any idea?
Thanks
