### ISSUE TITLE
SSR support. Fix window is not defined error

### ISSUE THREAD

**Issue by vpetrusevici** [sneas/img-comparison-slider#73]
Is it possible to add check like 
`if (typeof window !== 'undefined')`
in this place https://github.com/sneas/img-comparison-slider/blob/15f44f27d48f0f3a320eb540e4d8549e6fdc409b/src/index.ts#L396 ?
Because for now Angular Universal throw error 'window is not defined'.
I can create a PR if you do not mind

**Comment by sneas** [comment]
Hi @vpetrusevici, yes, please do. Thank you in advance!

**Comment by vpetrusevici** [comment]
PR is ready

**Comment by vpetrusevici** [comment]
So fast! Thanks!

**Comment by sneas** [comment]
CI/CD 💪
