### ISSUE TITLE
[vue/no-deprecated-slot-attribute] `slot` attributes are deprecated.

### ISSUE THREAD

**Issue by Arkitect-z** [sneas/img-comparison-slider#76]
I met this problem while programing, how to solve this, please.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/53122135/160272931-b46ffb88-9536-44d7-a975-512da106e82c.png">
<img width="461" alt="image" src="https://user-images.githubusercontent.com/53122135/160272947-3ba0e148-4e30-42cc-95b1-11408a6fa5f8.png">
<img width="293" alt="image" src="https://user-images.githubusercontent.com/53122135/160272977-9b5d5184-04aa-458b-b398-5452b4f833af.png">

**Comment by sneas** [comment]
Hi @Arkitect-z. Thank you for raising this issue. I've faced the same problem when I was experimenting with Vue. To be honest, I don't have a straight answer to this, but I can offer some reasoning. The Web Component slots are what make img-comparison-slider flexible and powerful. The `slot` attribute is a valid and non-deprecated part of [Web Components specification](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot). Meanwhile, Vue framework's `slot` attribute (now `v-slot`) is not related to the Web Components specification per-se and the depreciation message is not related to the valid HTML `slot` attribute usage, but to the `slot` -> `v-slot` transition of the framework. Given this reasoning, I can't see any problem with using  `slot` attributes as they intended to be used: as a part of Web Components (or HTML) specification. Thus, I'd suggest suppress the eslint warning with `<!-- eslint-disable -->` or turning off the `vue/no-deprecated-slot-attribute` rule through ESLint config.

**Comment by Arkitect-z** [comment]
Thank you for replying, I'm a newbie of Vue, I tried a lot solutions to fix it, but all failed. This issue doesn't influence my code's running, I'll just let it be there(doge).
