### ISSUE TITLE
Disable handle change on dragging / keypresses (passthrough)

### ISSUE THREAD

**Issue by strarsis** [sneas/img-comparison-slider#79]
@sneas: Thanks for this great and really well-made slider component!
This image comparison component is great! I use it also for other stuff than just `<img>`s.

Can the handle change on dragging be disabled?
And also the handle change on key presses? The key presses aren't passed through to the children elements.

Currently there are no options for not adding the event listeners / adjusting them:
https://github.com/sneas/img-comparison-slider/blob/master/src/index.ts#L145-L154

**Comment by strarsis** [comment]
PRs that add these options:
- https://github.com/sneas/img-comparison-slider/pull/80
- https://github.com/sneas/img-comparison-slider/pull/81

**Comment by sneas** [comment]
Hi @strarsis, thank you for your PRs. I’m traveling right now and will give the PRs a look tonight or tomorrow.

**Comment by sneas** [comment]
Hey @strarsis, I've checked out one of the PRs and merged it. The new version (7.6.0) has been released. Unfortunately, I don't have enough time to review the second PR today. The PR requires some changes. If you have time, you can help me with applying those changes. Just have a look at my commits to the keyboard PR https://github.com/sneas/img-comparison-slider/pull/80/commits. I'll need to apply pretty much similar changes before merging the "control" PR.

Thank you for your PRs, you're awesome 👍
