### ISSUE TITLE
When re-mounting, value is automatically set to 50

### ISSUE THREAD

**Issue by sekthekey** [sneas/img-comparison-slider#85]
If you go to a page where there is a slider, then go to any other one and return to the slider again, then the separator will be exactly in the middle. The same thing will happen if you wrap the slider component in v-if.

**Comment by sneas** [comment]
Hi, restoring the state is out the component’s concern. The state could be restored with the help of ‘slide’ event and ‘value’ prop. You can see this component as a standard HTML input or textarea: they also do not restore their state automatically, but they provide a way to do that with the help of ‘change’ event and ‘value’ prop.

**Comment by sekthekey** [comment]
Hi! thank you very much for your answer. The problem has been solved. I added this code to the mounted hook `this.$refs.slider.value = VALUE`
