### ISSUE TITLE
hint-icon is not visible all the time

### ISSUE THREAD

**Issue by Usamaahmad751** [sneas/img-comparison-slider#9]
Hi! I love this wonderful plugin. I really appreciate your efforts in coding this great plugin. But I was wondering if there is an option to make hint-icon always visible on the images. For now, It disappears when we slide the image but If we want to make it visible all the time?

**Comment by sneas** [comment]
Hi, thank you for your kind words! I’m going to provide this functionality this week.

**Comment by Usamaahmad751** [comment]
Nice to hear that! I will be waiting for this update. One more thing I noticed in the mobile version we have to tap to move the slider. As I just added it to this website https://axcelior.com. As you can see its too difficult to use the comparison slider in mobile version.  So, it would be great if you work on it to make a proper mobile user experience. Thanks Again!

**Comment by sneas** [comment]
Hi Usama, the new version has been just released. I updated the example https://sneas.github.io/img-comparison-slider/. Soon I plan to provide proper documentation, but you can apply the following CSS variables to the comparison slider component:

```
--hint-opacity: 0.5;
--hint-opacity-active: 0.5;
```

Opacity could be of any value and the slider will not disappear as soon as `--hint-opacity == --hint-opacity-active`.

**Comment by sneas** [comment]
Btw, I can't see the issue on the mobile version of the website anymore. I can assume there was a horizontal scroll that has been removed.

**Comment by Usamaahmad751** [comment]
Hi Dmitry Snisarenko, It's now working perfectly. Thank you so much for the quick update.

**Comment by Usamaahmad751** [comment]
BTW, Why horizontal scrolling is removed from the mobile version? Users are not able to slide the images properly they have to tap on the screen to move the slider. As you can in the example website https://axcelior.com.
