### ISSUE TITLE
vue3: ImgComparisonSlider component does not pass props down to the web component

### ISSUE THREAD

**Issue by sneas** [sneas/img-comparison-slider#90]
# Code Example

```vue
<template>
  <ImgComparisonSlider direction="vertical">
    <!-- eslint-disable -->
    <img
        slot="first"
        style="width: 100%"
        src="https://img-comparison-slider.sneas.io/demo/images/before.webp"
    />
    <img
        slot="second"
        style="width: 100%"
        src="https://img-comparison-slider.sneas.io/demo/images/after.webp"
    />
    <!-- eslint-enable -->
  </ImgComparisonSlider>
</template>

<script>
import { ImgComparisonSlider } from '@img-comparison-slider/vue'

export default {
  name: 'App',
  components: {
    ImgComparisonSlider
  }
}
</script>
```

# Expected Behavior

`direction` option is applied and working.

# Current Behavior

`direction` option does not take effect.

# Some Insights

1. The `ImgComparisonSlider` is a simple wrapper for the web component. It could be found in https://github.com/sneas/img-comparison-slider/blob/5d201518be32307d81e8d51028b51c760aca0956/bindings/vue/src/index.ts
1. The example in action could be found in https://github.com/sneas/img-comparison-slider-vue-example
1. The attribute gets applied by HMR (run the app with `npm start` and change the `direction` option back and forth. It will be applied).

**Comment by Germain-condo-group** [comment]
Hey, just throwing my 2 cents about some findings.
I figured that doing something like so works

    ```<ImgComparisonSlider :hover="hover" tabindex="0" class="rendered">```

And then

```
    const hover = ref<string>(null!);

    onMounted(() => {
        hover.value = 'hover';
    });
```

or

```
    const hover = ref<string>(null!);

    nextTick(() => {
        hover.value = 'hover';
    });
```

My take on this it that for some reason the initial value passed down to the underlying library is overwritten, maybe if props were passed down only after initial mount in your wrapping library it wouldn't happen anymore.

Hope that might help :)

**Comment by sneas** [comment]
@Germain-condo-group, I just opened this issue to put a comment and close, because it's been fixed. I’m very sorry I have not responded earlier. I’m very appreciate your comment and your effort to help.

**Comment by sneas** [comment]
@Germain-condo-group I'm not familiar with the Vue internals, but apparently it sets component props before rendering the element. Those props were overriten in connectionCallback

9b676e213e1099c4296d6b48a2809179d9b47431 fixed it.
