### ISSUE TITLE
Align custom handle

### ISSUE THREAD

**Issue by pwnz22** [sneas/img-comparison-slider#95]
How can i align to the end custom handle? Can i somehow change `handle-container` styles!?

**Comment by sneas** [comment]
Sorry, I can't clearly get the question. Would you like the custom handle to be placed not in the center of the divider, but rather at the top or bottom?

**Comment by pwnz22** [comment]
Thanks for reply. Yes, i want it to be at the bottom and also add some margin.

**Comment by sneas** [comment]
It is not possible so far using the component's API. But I was planning to implement it in the upcoming future. I'm busy with something else at the moment, but I'll do my best to deliver the solution in the upcoming weeks.
