### ISSUE TITLE
How to change the slider position only by dragging the handle, and set hover effect to the second slot

### ISSUE THREAD

**Issue by JarvisChao** [sneas/img-comparison-slider#99]
As the video, how to trigger slider only by dragging the handle and get "--exposure" value in the second element to set block width for hover

https://user-images.githubusercontent.com/38325453/195651743-afb36a31-b4b4-4bfd-92bd-185fa9b2c387.mov

**Comment by sneas** [comment]
Hi, thank you for the video. Unfortunately, adding a hyperlink in one of the slots is impossible with the current component. I've just experimented with the possibility of changing the slider position only by dragging the handle, and it seems doable. I think I can provide a solution in the upcoming weekend.

**Comment by sneas** [comment]
If you update the library to `v7.8.0`, you can set the `handle` attribute the component. Something like that`<img-comparison-slider handle>`. This will make the slider move only by the handle. Unfortunately, I have no easy recipe for making hover functionality work on the second slot but not on the first slot + the handle attribute is enabled. This will require some refactoring. I'm not ready for this right now.

**Comment by JarvisChao** [comment]
> If you update the library to `v7.8.0`, you can set the `handle` attribute on the component. Something like that`<img-comparison-slider handle>`. This will make the slider move only by the handle. Unfortunately, I have no easy recipe for making hover functionality work on the second slot but not on the first slot + the handle attribute is enabled. This will require some refactoring. I'm not ready for this right now.

Hi~
After testing, I found that there have dragging problems in the mobile.

https://user-images.githubusercontent.com/38325453/198326200-a3191331-35e8-464f-a049-5ffea2ca82c9.mov

**Comment by alvintheodora** [comment]
Hi @sneas , I used `"@img-comparison-slider/vue": "^8.0.0",`
And applied the `handle` like this:

```
<ImgComparisonSlider handle>
      <!-- eslint-disable -->
      <img
        slot="first"
        style="width: 100%"
        src="https://img-comparison-slider.sneas.io/demo/images/before.webp"
      />
      <img
        slot="second"
        style="width: 100%"
        src="https://img-comparison-slider.sneas.io/demo/images/after.webp"
      />
      <!-- eslint-enable -->
    </ImgComparisonSlider>
```

But, it seems that the handle is not working though.
Cheers

**Comment by sneas** [comment]
Hi @alvintheodora, you've found a bug. It's just been fixed in the latest version of `img-comparison-slider.` Thank you for your collaboration!

**Comment by alvintheodora** [comment]
That's blazing fast reaction, thank you!
